### ISSUE TITLE
This tool is making fun of the weakest members of society.

### ISSUE THREAD

**Issue by ghost** [rhgraysonii/hobos#1]
This repository is making fun of the weakest member of society, and even though it might be sarcasm, it's not ok.

People that are homeless face social marginalization and often violence.
Making their culture into satire, or romanticising their condition (however you want to see it) helps enforcing the stigmatisation that they face in society, and numbs people to their suffering.

I would expect you to at least raise awareness for the suffering of those in need, by linking to organisations that try to raise awareness and alleviate homelessness like [volunteers of america](http://www.voa.org/homeless-people) or [the national coalition for the homeless](http://nationalhomeless.org).

**Comment by ybur-yug** [comment]
This is a really good suggestion. Thanks @j-pb. 

I've actually lived on the streets myself (not joking). I personally donate to a shelter in Portland, Oregon (where I was at the time of my stint). I will add both links right now. The intention was not to ever make fun. I was actually using it as a slightly more entertaining lorem ipsum generator for seeding names in a db. I appreciate you opening the issue.

I apologize for the insensitivity, and will add those links and a couple others I find beneficial. I especially think mentioning SF might be of use, since the problem there is so large.

**Comment by ybur-yug** [comment]
I have updated the README, @j-pb and pushed to master. If you have any other suggestions, I will leave this open for a while and gladly will discuss it. If you truly think the repository has grounds to be removed, I would be willing to do so. However my personal thought is while `hobo` is a defined word, that is in the dictionary in the form of what it is referencing here, the issue that this came from was using the "r-word" ina  derogatory manner/slur, due to its definition being:

```
Delay or hold back in terms of progress, development, or accomplishment.
```

This obviously has to be stretched/abused to be offensive in language, which was why I was uncomfortable with the issue in the last thread.

Anywho, I really do appreciate it and am happy to discuss.

**Comment by ybur-yug** [comment]
It might even be good to add a note that will print something alone the lines of what is referenced in the README on the first run of the program from the CLI

**Comment by ghost** [comment]
I think this is a good solution.

Btw I think this would be a far better solution to the mentioned issue.
If github finds objectionable content, they could put a link to the relevant organisations on the bottom of the page.

As someone facing serious disability dues to multiple sclerosis, I'd be far happier with people using the horrible words to describe my disease, speaking about it, and getting informed about it.
Than removing all mention of the disease and its consequences, and cushioning the rest in nice words, so nobody needs to be scared.

It's better for me that people talk about it (even in an abusive context) than people forgetting about it.
Forgetting it won't get people pay for the research and social security, talking about it might.

"I'd rather be a cripple with a feared and researched disease, than a differently abled with a status quo."

**Comment by ybur-yug** [comment]
I agree with you completely. I think it boils down largely to the need to lack 'objectionable' content on a corporate level as they have larger and larger corporations with public-facing aspects signing on (and walk toward that path themselves). It largely is a manifestation of the combination of this and the social community around it.

However, I do think that when speaking on things such as mental disabilities there are technical, non-blanket terms. eg 'cripple' vs 'parapalegic', I would think the latter is obviously acceptable and the former questionable/offensive. I think the use of the 'r-word' in the other thread is an example of this. 

I wish you the best. My moms best friend has had MS my entire life, and I've seen how much havok it can wreak. Happy hacking & stay in the best health you can.

**Comment by ghost** [comment]
'parapalegic' doesn't properly convey the fear and desperation though.
Like I said, the more neutral and technical a term is, the less urgent people will perceive my disease.
[See George Charlins bit on 'shell shock'.](https://www.youtube.com/watch?v=hSp8IyaKCs0)

**Comment by ybur-yug** [comment]
Will do. I really appreciate your insight and working with me instead of starting a flame war that goes nowhere such as where we came from. :100: :+1:

Bookmarked. I'm on a netflix binge but it shall be up next. I love Carlin.

**Comment by ghost** [comment]
Sure, likewise :), least we can do :)
